spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      stat-view-servlet:
        enabled: true # StatViewServlet配置,开启后可以看到druid默认监控html
        allow: 192.168.1.160
      #        login-username: rtc
      #        login-password: 111
      web-stat-filter:
        enabled: false # WebStatFilter配置
      filter:
        stat:
          enabled: true
          log-slow-sql: true #开启后记录超过slow-sql-millis指定时间的SQL到日志中 slow sql xx millis. SQL
          slow-sql-millis: 3000 #超过指定毫秒的SQL会在SQL监控里变红
          merge-sql: true # 合并SQL，在SQL监控里使用?代替不同参数的同一SQL
        wall:
          enabled: false # 开启后可以防御指定SQL～加入到黑名单 sql injection violation, dbType mysql, druid-version 1.2.1, select not allow : SQL
          config:
            multi-statement-allow: true # 是否允许批量SQL
      filters: stat,wall,config # 配置后哪些可以看到,stat:SQL监控页面,wall:防火墙
      url: jdbc:mysql://localhost:3306/rtc?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=True&serverTimezone=UTC
#      url: jdbc:mysql://localhost:3306/rtc_android?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=True&serverTimezone=UTC
      username: root
      password: IywBSNTqJNbQ4fxk386Je8QGHdK5ZsX1JepnL/2h/cB8i42Neg3Lj8JiHD9iUbzEY5t+3k718eknwLCK086kpw==
      connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMJS6B3QFwE5ypsNTa2CkeDhI7dC4aNJ13D9LYZpJsAiYaXWexj5f0dRpqCxKot2VIzUMqxuVPmUADjfmGKLrf0CAwEAAQ==
  #            time-between-log-stats-millis: 3000 #配置每xx毫秒输出一次统计日志,并清除druid页面的SQL监控数据

  redis:
    host: localhost
    timeout: 3000
    port: 6379
    database: 0
    lettuce:
      pool:
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 8 # 连接池中的最大空闲连接
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）

  mail:
    properties:
      mail:
        stmp:
          connection: 30
          timeout: 30
          writetimeout: 30
  servlet:
    multipart:
      max-file-size: 5MB

server:
  port: 9998

mybatis:
  mapperLocations: classpath:mapper/*.xml

logging:
  level:
    com.rtc.manager: info
  file:
    path: /work/log
#  config: src/main/resources/config/logback.xml


pagehelper:
  #分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
  helper-dialect: mysql
  #Mapper传入pageNum,pageSize参数,不需要写额外SQL,service层调用时候传入即可
  reasonable: true

swagger:
  enable: true

rtc:
  url: http://192.168.1.125
  mail:
    redisEmailLimt: 1000
  portrait:
    #    /Users/chenhang/work/portrait
    #    实际保存位置
    /home/work/portrait
  #  对外暴露位置
  portraitURI:
    http://192.168.1.125/portrait
  # 评论长度限制
  commitLength:
    1000
  # 验证码过期时间(minutes)
  verificationCodeTTL:
    15
  # 登录token过期时间(day)
  loginTokenTTL:
    30
  comment-stars:
    0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5
  timezone:
    -18, -17, -16, -15, -14, -13, -12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1,
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18
  esIndices:
    china, india-cin, india-llpin, vietnam, america-alabama, america-newhampshire, america-northcarolina, canada

