spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rtc?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=True&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9981

mybatis:
  mapperLocations: classpath:mapper/*.xml

logging:
  level:
    com.rtc.manager: info
  file:
    path: /work/log
#  config: src/main/resources/config/logback.xml


pagehelper:
#分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
  helper-dialect: mysql
#Mapper传入pageNum,pageSize参数,不需要写额外SQL,service层调用时候传入即可
  reasonable: true

rtc:
  url: "http://192.168.1.125"
