spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rtc?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=True
    username: root
    password: Ch2757948
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9981

mybatis:
  mapperLocations: classpath:mapper/*.xml

logging:
  level:
    com.rtc.manager.dao: debug
#  file:
#    path: /Users/chenhang/Documents/log
#  config: src/main/resources/config/logback.xml